### PR TITLE
Add minimal FP test

### PR DESCRIPTION
**Pull request by the-storm**
### Summary
This is a minimal test showing a false positives when the DSL mark params as sources but then there is a `setter` that should override the taint 
Example code
```
  public final void fp1_expected(UserBlob u) {
    u.setF1("Not_tainted");
    Origin.sink(u.getF2());
  }
```

### Testing
Added an e2e test demonstrating the FP

### CODE REVIEW

**Comment by arthaud** [comment]
The false positive is caused by the analysis not inferred strong updates and just assuming weak updates. This is a problem for most of our taint analyzers.

I think we cover that problem in this test: https://github.com/facebook/mariana-trench/blob/main/source/tests/integration/end-to-end/code/strong_update/Flow.java

If you still want to add your test, could you add it to that file/folder? Thanks.

**Review by arthaud — CHANGES_REQUESTED** [review]
cf previous comment

**Comment by the-storm** [comment]
> The false positive is caused by the analysis not inferred strong updates and just assuming weak updates. This is a problem for most of our taint analyzers.
> 
> I think we cover that problem in this test: https://github.com/facebook/mariana-trench/blob/main/source/tests/integration/end-to-end/code/strong_update/Flow.java
> 
> If you still want to add your test, could you add it to that file/folder? Thanks.

Thanks for the context! Is there an ETA for fixing this issue? and are there any ways mitigate such FPs until it is fixed? 
For context, this does affect many Java framework e.g., Springframework when specifying the arguments as entry points.

**Comment by arthaud** [comment]
I don't think this has been bothering us too much, so we haven't prioritized fixing this.
If you know that the setters only update one field and do nothing else, you could use a model generator that finds those setters and add the `strong-write-on-propagation` mode.

**Comment by the-storm** [comment]
@arthaud  happy to drop the test if it is not adding new coverage. I think most of the test body is covered also by https://github.com/facebook/mariana-trench/blob/3e8c2ecfa2e9a0e783ac8c0d3ec8ba90b5ebf556/source/tests/integration/end-to-end/code/access_paths/AccessPaths.java#L67-L74 

However, I am not sure what. I am doing wrong. I updated the configs and added `strong-write-on-propagation` but the false positive is still surfaced. Any idea what I might be missing?

**Comment by arthaud** [comment]
> @arthaud happy to drop the test if it is not adding new coverage. I think most of the test body is covered also by

I think your test is slightly different so it could be useful to have it.
Since I had to investigate, I merged this test into `end-to-end/code/strong_update/Flow.java` internally and will be landing this soon.

> However, I am not sure what I am doing wrong. I updated the configs and added `strong-write-on-propagation` but the false positive is still there. Any idea what I might be missing?

Alright, I tested this locally and you are right, this doesn't work.
It's more complicated than it looks. This is a problem caused by analyzing low-level bytecode.
What we see is just an `invoke v1, v0, UserBlob.setF1`, hence we don't really know that `v0` will be a string (without taint) later on, we can't really apply the `strong-write-on-propagation`.
I don't think there is a work around this, unfortunately.
I also think it might be complex to fix this. I need to think more about this.

**Comment by arthaud** [comment]
I thought more about this. I think this could be solved by using something like `inline-as`. We currently detect simple getters and inline them. We could do the same for setters.

**Comment by the-storm** [comment]
> For the cases you care about, are the setters always trivial, i.e this.field = argument without any extra code?

Sorry for the late reply, I was OTG. Yep most of the setters I care about are just simple setters, take an argument set a field and return. 

Can you walk me through how the in-line as work or is that something you can support from your side?

**Comment by arthaud** [comment]
`inline_as` is something that the analysis infers automatically.
For now, it detects simple getters of the form `return this.field`.
It can then be used at the call site of getters, to improve precision. Without it, we would assume that the method call returns a new "memory location" that doesn't alias the field.
This allows us to properly find taint for stuff like:
```
Object x = this.getFoo();
this.foo = source();
sink(x); // We know x and this.foo refer to the same object in memory
```
This is inferred here: https://github.com/facebook/mariana-trench/blob/main/source/ForwardAliasTransfer.cpp#L331
And use here: https://github.com/facebook/mariana-trench/blob/main/source/TransferCall.cpp#L143
I can try implementing it for setters on my spare time but can't promise anything, as it's not high priority for us.

**Comment by arthaud** [comment]
This should be fixed by 751bafa763cc544c5b05780897350ee08d36c17a
Please re-open in case you are still having false positives :)

**Comment by the-storm** [comment]
> This should be fixed by [751bafa](https://github.com/facebook/mariana-trench/commit/751bafa763cc544c5b05780897350ee08d36c17a) Please re-open in case you are still having false positives :)

thanks for fixing this. Let me validate locally and get back to you

**Comment by arthaud** [comment]
Alright, I just checked.
I think this is because your model generator taints `u` (i.e, `Argument(x)`) entirely. So even though we call `u.setF1("Not_tainted")`, `u` itself is still tainted.
If you update your model generator to only taint `f1` (using `Argument(x).f1`) then the issue goes away.

**Comment by the-storm** [comment]
closing this PR now as it is a no-op

**Pull request closed without merging**
